### ISSUE TITLE
Modeltest for DNA substitution model

### ISSUE THREAD

**Issue by BEAST-Community** [sdwfrost/mevr-course-2016#3]
@sdwfrost Could you use jModelTest2 to do model test, rather than modeltest?

**Comment by BEAST-Community** [comment]
@sdwfrost Could you please attach the RAxML software that used to do RAxml analysis.

**Comment by sdwfrost** [comment]
You can do anything you want for modeltest, they should all be broadly comparable. It doesn't make sense to package up RAxML given that releases (and up to date ones too) are found here:

[https://github.com/stamatak/standard-RAxML](https://github.com/stamatak/standard-RAxML)
