### ISSUE TITLE
How to call raxml?

### ISSUE THREAD

**Issue by BEAST-Community** [sdwfrost/mevr-course-2016#4]
@sdwfrost Could you tell me how to call raxml?

**Comment by sdwfrost** [comment]
In R? You'd use `system.call`, or if you're running an RMarkdown document in RStudio, you can execute shell commands rather easily. You may also be interested in some smaller, but more up to date courses:

[https://github.com/sdwfrost/mevr-course-ghana/blob/gh-pages/index.ipynb](https://github.com/sdwfrost/mevr-course-ghana/blob/gh-pages/index.ipynb)

[https://github.com/sdwfrost/kemri-phylodynamics](https://github.com/sdwfrost/kemri-phylodynamics)

**Comment by sdwfrost** [comment]
Also, do you look at the actual course notes:

[http://sdwfrost.github.io/mevr-course-2016/](http://sdwfrost.github.io/mevr-course-2016/)

Much easier to go through!

**Comment by BEAST-Community** [comment]
@sdwfrost In your R Markdown: https://github.com/sdwfrost/mevr-course-2016/blob/master/ml/raxml.Rmd:
myalignment.rax.gtr <- raxml (myalignment,
      m="GTRGAMMAIX", # model
      f="a", # best tree and bootstrap
      p=1234, # random number seed
      x=2345, # random seed for rapid bootstrapping
      N=100, # number of bootstrap replicates
      file="ray2000", # name of output files
      exec="raxmlHPC-PTHREADS-SSE3", # name of executable
      threads=2
      )
Can the above code aotumate call  "raxmlHPC-PTHREADS-SSE3"  or I have to put "raxmlHPC-PTHREADS-SSE3.exe" in the respective file, thanks.
